### ISSUE TITLE
"The Kubernetes deployment for this container should be configured so that the container is restarted as soon as check.sh returns a non-zero exit code."

### ISSUE THREAD

**Issue by stephanlindauer** [Baljan/gke-static-ip#1]
hi, 
thanks for this project. i was wondering what the logic mentioned in the topic accomplishes. is this so the pod would reschedule on a different node? the problem i am currently having is that the node that needs to get the external ip assigned cannot be the one who is executing those commands because it will no be able to talk to the google api anymore as soon as the old network interface is detached.
would be cool if you could explain how this project gets around this issue.
thanks! :)

**Comment by patriksletmo** [comment]
Hey!

This project is designed to be used in a single node setup on GKE, but I think it should be applicable to your problem as well.

The reason for making the container restart as soon as `check.sh` returns a non-zero exit code is because the container makes modifications to the static IP on startup only. However, the container logic is very dynamic and it does not need to check the IP of the node it is running on. If you can make [the variable INSTANCE](https://github.com/Baljan/gke-static-ip/blob/master/check.sh#L4) in `check.sh` and `apply.sh` resolve to the node that requires a static IP you can place the `gke-static-ip` container anywhere you want.

You might be able to solve this by configuring the `INSTANCE_PREFIX` appropriately, but you might also need to use another technique for resolving the correct node/instance depending on your setup. We have no plans for adding such functionality to this container image ourselves (correct me if I'm wrong @teori), but feel free to submit a pull request!

**Comment by stephanlindauer** [comment]
thanks for your response! i think i should clarify my question a bit more.
basically i don't understand how this would work on just one node. my understanding is:
1. https://github.com/Baljan/gke-static-ip/blob/master/apply.sh#L22 gets executed
2. network interface is detached from the node this code is running on
3. node is left without a network interface to talk to the google api
4. https://github.com/Baljan/gke-static-ip/blob/master/apply.sh#L23 will never be executed due to missing connectivity

so i am curious as to why this works in your setup while it doesn't work in mine (i am a google cloud noob so maybe i am missing something here).

**Comment by stephanlindauer** [comment]
so it turns out this only works if `private_ip_google_access` is enabled for the subnet of the node, which it wasn't in my case. :grimacing:

**Comment by patriksletmo** [comment]
Well, that explains why it didn't work! Are you okay with me closing this issue?

I don't know if we have `private_ip_google_access` enabled in our setup since we haven't taken any active choice in enabling it. You reasoning around the detached network interface seems very plausible though. I was under the impression that only the incoming traffic was affected by the change at https://github.com/Baljan/gke-static-ip/blob/master/apply.sh#L22, but that might not be the case.

**Comment by stephanlindauer** [comment]
:+1:
